### ISSUE TITLE
style scoped only supported in firefox

### ISSUE THREAD

**Issue by thomaspark** [thomaspark/snowball#47]
need polyfill for other browsers

**Comment by thomaspark** [comment]
https://github.com/thingsinjars/jQuery-Scoped-CSS-plugin
https://github.com/PM5544/scoped-polyfill

**Comment by thomaspark** [comment]
Prefer the scoped-polyfill approach (generate IDs and prepend to selectors) but can't get it working. Opened an issue.

Will use jQuery-Scoped (inline styles) in the meantime. It works fairly well, but has its own problems (mass inline styles on all descendants, background-attachment is ignored) that I've opened an issue for.

**Comment by thomaspark** [comment]
jQuery-Scoped turned out to have its own share of bugs, so removed it for now.

Considering using LESS/CSS to scope it to each block's unique ID, and generating CSS for published article. For example:

``` css
blockquote {
  font-size: 16px;
}
```

gets wrapped as:

``` less
#snowball-block-1 {
  blockquote {
    font-size: 16px;
  }
}
```

which generates:

``` css
#snowball-block-1 blockquote {
  font-size: 16px;
}
```
